theme: minima
title: Github Pages Learning Lab
author: Muhamed Fazeel K A 
email: dev.appstrial@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my Github Pages Tutorial

# social links
twitter_username: NIL # DO NOT include the @ character, or else the build will fail!
github_username:  Fazeel642 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
